In [ ]:
! pip install PyPDF2

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.4 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1

In [ ]:
import PyPDF2

In [ ]:
import os
from PyPDF2 import PdfReader, PdfWriter

In [ ]:
def split_pdf(input_pdf_path, output_folder):
    # Open the PDF file
    with open(input_pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)

        # Iterate through each page in the PDF
        for page_num in range(num_pages):
            # Create a new PDF writer for each page
            writer = PdfWriter()

            writer.add_page(pdf_reader.pages[page_num])

            # Output file name for each page
            output_filename = f"{output_folder}/page_{page_num + 1}.pdf"

            # Write the page to a new PDF file
            with open(output_filename, 'wb') as output_file:
                writer.write(output_file)

# Example usage:
input_pdf_path = "/content/cnt_efc311217.pdf"  # Change this to your input PDF file
output_folder = "/content/drive/MyDrive/bunch"  # Change this to the folder where you want to save the individual PDFs
split_pdf(input_pdf_path, output_folder)

In [ ]:
from PIL import Image
import cv2
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
#!pip install paddlepaddle-gpu==2.3.2 cudatoolkit==10.2

In [ ]:
!pip install paddlepaddle-gpu==2.3.0.post110 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

Looking in links: https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
Collecting paddlepaddle-gpu==2.3.0.post110
  Downloading https://paddle-wheel.bj.bcebos.com/2.3.0/linux/linux-gpu-cuda11.0-cudnn8-mkl-gcc8.2-avx/paddlepaddle_gpu-2.3.0.post110-cp310-cp310-linux_x86_64.whl (532.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 532.9/532.9 MB 914.0 kB/s eta 0:00:00
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu==2.3.0.post110) (2.31.0)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu==2.3.0.post110) (1.25.2)
Requirement already satisfied: protobuf>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu==2.3.0.post110) (3.20.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu==2.3.0.post110) (9.4.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu==2.3.0.post110) (1.16.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu==2.3.0.post110) (4.4.2)
Collecting astor (from paddlepaddle-gpu==2.3.0.post110)
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting paddle-bfloat==0.1.2 (from paddlepaddle-gpu==2.3.0.post110)
  Downloading paddle_bfloat-0.1.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (375 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 375.7/375.7 kB 3.4 MB/s eta 0:00:00
Requirement already satisfied: opt-einsum==3.3.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu==2.3.0.post110) (3.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20.0->paddlepaddle-gpu==2.3.0.post110) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20.0->paddlepaddle-gpu==2.3.0.post110) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20.0->paddlepaddle-gpu==2.3.0.post110) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20.0->paddlepaddle-gpu==2.3.0.post110) (2024.2.2)
Installing collected packages: paddle-bfloat, astor, paddlepaddle-gpu

# pdf2image

## Installation

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install pdf2image
!apt-get update
!apt-get install poppler-utils

Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from pdf2image) (9.4.0)
Installing collected packages: pdf2image
Successfully installed pdf2image-1.17.0
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:7 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [52.9 kB]
Hit:8 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease [24.3 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,035 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,370 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1,755 kB]
Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [28.3 kB]
Get:16 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy/main amd64 Packages [44.2 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,077 kB]
Fetched 6,747 kB in 5s (1,265 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 50 not upgraded.
Need to get 186 kB of archives.
After this operation, 696 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.3 [186 kB]
Fetched 186 kB in 0s (926 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 121752 files and directories currently installed.)
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.3_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.3) ...
Setting up poppler-utils (22.02.0-2ubuntu0.3) ...
Processing triggers for man-db (2.10.2-1) ...

## Conversion

In [ ]:
from pdf2image import convert_from_path

In [ ]:
images = convert_from_path('/content/page_2.pdf')

In [ ]:
!mkdir pages

mkdir: cannot create directory ‘pages’: File exists

In [ ]:
for i in range(len(images)):
  images[i].save('pages/page'+str(i)+'.jpg','JPEG')

# Layout

## Installation

In [ ]:
!python3 -m pip install paddlepaddle-gpu

Requirement already satisfied: paddlepaddle-gpu in /usr/local/lib/python3.10/dist-packages (2.3.0.post110)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (2.31.0)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (1.25.2)
Requirement already satisfied: protobuf>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (3.20.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (10.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (1.16.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (4.4.2)
Requirement already satisfied: astor in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (0.8.1)
Requirement already satisfied: paddle-bfloat==0.1.2 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (0.1.2)
Requirement already satisfied: opt-einsum==3.3.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle-gpu) (3.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20.0->paddlepaddle-gpu) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20.0->paddlepaddle-gpu) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20.0->paddlepaddle-gpu) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20.0->paddlepaddle-gpu) (2024.2.2)

In [ ]:
!pip install "paddleocr>=2.0.1"
!pip install protobuf==3.20.0
#!git clone https://github.com/Benziela/PaddleOcrFineTuning.git
!git clone https://github.com/PaddlePaddle/PaddleOCR.git

Collecting paddleocr>=2.0.1
  Downloading paddleocr-2.7.3-py3-none-any.whl (780 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.0/780.0 kB 4.1 MB/s eta 0:00:00
Requirement already satisfied: shapely in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (2.0.4)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (0.19.3)
Requirement already satisfied: imgaug in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (0.4.0)
Collecting pyclipper (from paddleocr>=2.0.1)
  Downloading pyclipper-1.3.0.post5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (908 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 908.3/908.3 kB 19.0 MB/s eta 0:00:00
Collecting lmdb (from paddleocr>=2.0.1)
  Downloading lmdb-1.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (299 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.2/299.2 kB 29.4 MB/s eta 0:00:00
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (4.66.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (1.25.2)
Collecting visualdl (from paddleocr>=2.0.1)
  Downloading visualdl-2.5.3-py3-none-any.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 46.4 MB/s eta 0:00:00
Collecting rapidfuzz (from paddleocr>=2.0.1)
  Downloading rapidfuzz-3.8.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 37.1 MB/s eta 0:00:00
Collecting opencv-python<=4.6.0.66 (from paddleocr>=2.0.1)
  Downloading opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 MB 7.4 MB/s eta 0:00:00
Collecting opencv-contrib-python<=4.6.0.66 (from paddleocr>=2.0.1)
  Downloading opencv_contrib_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (67.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 MB 5.4 MB/s eta 0:00:00
Requirement already satisfied: cython in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (3.0.10)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (4.9.4)
Collecting premailer (from paddleocr>=2.0.1)
  Downloading premailer-3.10.0-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (3.1.2)
Collecting attrdict (from paddleocr>=2.0.1)
  Downloading attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
Collecting Pillow>=10.0.0 (from paddleocr>=2.0.1)
  Downloading pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 18.6 MB/s eta 0:00:00
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (6.0.1)
Collecting python-docx (from paddleocr>=2.0.1)
  Downloading python_docx-1.1.0-py3-none-any.whl (239 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.6/239.6 kB 12.7 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (4.12.3)
Requirement already satisfied: fonttools>=4.24.0 in /usr/local/lib/python3.10/dist-packages (from paddleocr>=2.0.1) (4.51.0)
Collecting fire>=0.3.0 (from paddleocr>=2.0.1)
  Downloading fire-0.6.0.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pdf2docx (from paddleocr>=2.0.1)
  Downloading pdf2docx-0.5.8-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 kB 14.6 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fire>=0.3.0->paddleocr>=2.0.1) (1.16.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from fire>=0.3.0->paddleocr>=2.0.1) (2.4.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->paddleocr>=2.0.1) (2.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from imgaug->paddleocr>=2.0.1) (1.11.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from imgaug->paddleocr>=2.0.1) (3.7.1)
Requirement already satisfied: imageio in /usr/local/lib/python3.10/dist-packages (from imgaug->paddleocr>=2.0.1) (2.31.6)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.10/dist-packages (from scikit-image->paddleocr>=2.0.1) (3.3)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.10/dist-packages (from scikit-image->paddleocr>=2.0.1) (2024.4.18)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-image->paddleocr>=2.0.1) (1.6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from scikit-image->paddleocr>=2.0.1) (24.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl->paddleocr>=2.0.1) (1.1.0)
Collecting PyMuPDF>=1.19.0 (from pdf2docx->paddleocr>=2.0.1)
  Downloading PyMuPDF-1.24.2-cp310-none-manylinux2014_x86_64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 52.6 MB/s eta 0:00:00
Requirement already satisfied: opencv-python-headless>=4.5 in /usr/local/lib/python3.10/dist-packages (from pdf2docx->paddleocr>=2.0.1) (4.9.0.80)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from python-docx->paddleocr>=2.0.1) (4.11.0)
Collecting cssselect (from premailer->paddleocr>=2.0.1)
  Downloading cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Collecting cssutils (from premailer->paddleocr>=2.0.1)
  Downloading cssutils-2.10.2-py3-none-any.whl (398 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.1/398.1 kB 11.2 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from premailer->paddleocr>=2.0.1) (2.31.0)
Requirement already satisfied: cachetools in /usr/local/lib/python3.10/dist-packages (from premailer->paddleocr>=2.0.1) (5.3.3)
Collecting bce-python-sdk (from visualdl->paddleocr>=2.0.1)
  Downloading bce_python_sdk-0.9.7-py3-none-any.whl (331 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.5/331.5 kB 28.1 MB/s eta 0:00:00
Requirement already satisfied: flask>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from visualdl->paddleocr>=2.0.1) (2.2.5)
Collecting Flask-Babel>=3.0.0 (from visualdl->paddleocr>=2.0.1)
  Downloading flask_babel-4.0.0-py3-none-any.whl (9.6 kB)
Requirement already satisfied: protobuf>=3.20.0 in /usr/local/lib/python3.10/dist-packages (from visualdl->paddleocr>=2.0.1) (3.20.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from visualdl->paddleocr>=2.0.1) (2.0.3)
Collecting rarfile (from visualdl->paddleocr>=2.0.1)
  Downloading rarfile-4.2-py3-none-any.whl (29 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from visualdl->paddleocr>=2.0.1) (5.9.5)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (3.0.2)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (3.1.3)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (2.2.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (8.1.7)
Requirement already satisfied: Babel>=2.12 in /usr/local/lib/python3.10/dist-packages (from Flask-Babel>=3.0.0->visualdl->paddleocr>=2.0.1) (2.14.0)
Requirement already satisfied: pytz>=2022.7 in /usr/local/lib/python3.10/dist-packages (from Flask-Babel>=3.0.0->visualdl->paddleocr>=2.0.1) (2023.4)
Collecting Pillow>=10.0.0 (from paddleocr>=2.0.1)
  Downloading Pillow-10.0.1-cp310-cp310-manylinux_2_28_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 57.2 MB/s eta 0:00:00
Collecting PyMuPDFb==1.24.1 (from PyMuPDF>=1.19.0->pdf2docx->paddleocr>=2.0.1)
  Downloading PyMuPDFb-1.24.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (30.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.8/30.8 MB 31.6 MB/s eta 0:00:00
Collecting pycryptodome>=3.8.0 (from bce-python-sdk->visualdl->paddleocr>=2.0.1)
  Downloading pycryptodome-3.20.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 79.6 MB/s eta 0:00:00
Requirement already satisfied: future>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from bce-python-sdk->visualdl->paddleocr>=2.0.1) (0.18.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug->paddleocr>=2.0.1) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug->paddleocr>=2.0.1) (0.12.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug->paddleocr>=2.0.1) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug->paddleocr>=2.0.1) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug->paddleocr>=2.0.1) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->visualdl->paddleocr>=2.0.1) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->premailer->paddleocr>=2.0.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->premailer->paddleocr>=2.0.1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->premailer->paddleocr>=2.0.1) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->premailer->paddleocr>=2.0.1) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.0->flask>=1.1.1->visualdl->paddleocr>=2.0.1) (2.1.5)
Building wheels for collected packages: fire
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.6.0-py2.py3-none-any.whl size=117029 sha256=bb924114a1526e6ae093cad0a8166935c6f884cbd97b34f1ce808e0d100af274
  Stored in directory: /root/.cache/pip/wheels/d6/6d/5d/5b73fa0f46d01a793713f8859201361e9e581ced8c75e5c6a3
Successfully built fire
Installing collected packages: pyclipper, lmdb, rarfile, rapidfuzz, python-docx, PyMuPDFb, pycryptodome, Pillow, opencv-python, opencv-contrib-python, fire, cssutils, cssselect, attrdict, PyMuPDF, premailer, bce-python-sdk, pdf2docx, Flask-Babel, visualdl, paddleocr
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.4.0
    Uninstalling Pillow-9.4.0:
      Successfully uninstalled Pillow-9.4.0
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.8.0.76
    Uninstalling opencv-python-4.8.0.76:
      Successfully uninstalled opencv-python-4.8.0.76
  Attempting uninstall: opencv-contrib-python
    Found existing installation: opencv-contrib-python 4.8.0.76
    Uninstalling opencv-contrib-python-4.8.0.76:
      Successfully uninstalled opencv-contrib-python-4.8.0.76
Successfully installed Flask-Babel-4.0.0 Pillow-10.0.1 PyMuPDF-1.24.2 PyMuPDFb-1.24.1 attrdict-2.0.1 bce-python-sdk-0.9.7 cssselect-1.2.0 cssutils-2.10.2 fire-0.6.0 lmdb-1.4.1 opencv-contrib-python-4.6.0.66 opencv-python-4.6.0.66 paddleocr-2.7.3 pdf2docx-0.5.8 premailer-3.10.0 pyclipper-1.3.0.post5 pycryptodome-3.20.0 python-docx-1.1.0 rapidfuzz-3.8.1 rarfile-4.2 visualdl-2.5.3

Collecting protobuf==3.20.0
  Downloading protobuf-3.20.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.4 MB/s eta 0:00:00
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
ERROR: Operation cancelled by user
Cloning into 'PaddleOcrFineTuning'...
remote: Enumerating objects: 63603, done.

In [ ]:
!wget https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
!pip install -U layoutparser-0.0.0-py3-none-any.whl

--2024-04-27 10:53:13--  https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
Resolving paddleocr.bj.bcebos.com (paddleocr.bj.bcebos.com)... 103.235.46.61, 2409:8c04:1001:1203:0:ff:b0bb:4f27
Connecting to paddleocr.bj.bcebos.com (paddleocr.bj.bcebos.com)|103.235.46.61|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19145360 (18M) [application/octet-stream]
Saving to: ‘layoutparser-0.0.0-py3-none-any.whl’

layoutparser-0.0.0- 100%[===================>]  18.26M  3.25MB/s    in 15s

2024-04-27 10:53:30 (1.24 MB/s) - ‘layoutparser-0.0.0-py3-none-any.whl’ saved [19145360/19145360]

Processing ./layoutparser-0.0.0-py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from layoutparser==0.0.0) (1.25.2)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from layoutparser==0.0.0) (4.6.0.66)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from layoutparser==0.0.0) (2.0.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from layoutparser==0.0.0) (10.0.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from layoutparser==0.0.0) (6.0.1)
Collecting iopath (from layoutparser==0.0.0)
  Downloading iopath-0.1.10.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from layoutparser==0.0.0) (4.66.2)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.10/dist-packages (from iopath->layoutparser==0.0.0) (4.11.0)
Collecting portalocker (from iopath->layoutparser==0.0.0)
  Downloading portalocker-2.8.2-py3-none-any.whl (17 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->layoutparser==0.0.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->layoutparser==0.0.0) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->layoutparser==0.0.0) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->layoutparser==0.0.0) (1.16.0)
Building wheels for collected packages: iopath
  Building wheel for iopath (setup.py) ... done
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31532 sha256=3aac631dd3dca1a2e91d80d5be3b27baa991ee3e9f5121853f3cc1473cec7a20
  Stored in directory: /root/.cache/pip/wheels/9a/a3/b6/ac0fcd1b4ed5cfeb3db92e6a0e476cfd48ed0df92b91080c1d
Successfully built iopath
Installing collected packages: portalocker, iopath, layoutparser
Successfully installed iopath-0.1.10 layoutparser-0.0.0 portalocker-2.8.2

## Table Extraction

In [ ]:
!pip install paddlepaddle

Collecting paddlepaddle
  Downloading paddlepaddle-2.6.1-cp310-cp310-manylinux1_x86_64.whl (125.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.9/125.9 MB 5.1 MB/s eta 0:00:00
Collecting httpx (from paddlepaddle)
  Downloading httpx-0.27.0-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 8.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (1.25.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (10.0.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (4.4.2)
Requirement already satisfied: astor in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (0.8.1)
Requirement already satisfied: opt-einsum==3.3.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (3.3.0)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (3.20.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx->paddlepaddle) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx->paddlepaddle) (2024.2.2)
Collecting httpcore==1.* (from httpx->paddlepaddle)
  Downloading httpcore-1.0.5-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 9.5 MB/s eta 0:00:00
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx->paddlepaddle) (3.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx->paddlepaddle) (1.3.1)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx->paddlepaddle)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.9 MB/s eta 0:00:00
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->paddlepaddle) (1.2.1)
Installing collected packages: h11, httpcore, httpx, paddlepaddle
Successfully installed h11-0.14.0 httpcore-1.0.5 httpx-0.27.0 paddlepaddle-2.6.1

In [ ]:
import layoutparser as lp

In [ ]:
import cv2
image = cv2.imread("pages/page0.jpg")

In [ ]:
image = image[..., ::-1]

# load model
model = lp.PaddleDetectionLayoutModel(config_path="lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config",
                                threshold=0.5,
                                label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"},
                                enforce_cpu=False,
                                enable_mkldnn=True)#math kernel library
# detect
layout = model.detect(image)

In [ ]:
layout

Layout(_blocks=[TextBlock(block=Rectangle(x_1=94.51361083984375, y_1=57.2735595703125, x_2=1573.407958984375, y_2=2176.787109375), text=None, id=None, type=Figure, parent=None, next=None, score=0.9716271758079529)], page_data={})

In [ ]:
#x_1=88.26336669921875
#y_1=63.38427734375
#x_2=1580.184814453125
#y_2=2243.169921875

for l in layout:
  #print(l)
  if l.type == 'Figure' or l.type =='Table':
    x_1 = int(l.block.x_1)
    print(l.block.x_1)
    y_1 = int(l.block.y_1)
    x_2 = int(l.block.x_2)
    y_2 = int(l.block.y_2)

    break

94.51361

In [ ]:
print(x_1,y_1,x_2,y_2)

94 57 1573 2176

In [ ]:
im = cv2.imread('pages/page0.jpg')

In [ ]:
cv2.imwrite('ext_im.jpg', im[y_1:y_2,x_1:x_2])

True

# Text Detection and Recognition

In [ ]:
output

[[[[447.0, 190.0], [1050.0, 190.0], [1050.0, 221.0], [447.0, 221.0]],
  ('BILAN C0NS0LDE au 31/12/2017', 0.9731495976448059)],
 [[[614.0, 263.0], [889.0, 263.0], [889.0, 291.0], [614.0, 291.0]],
  ('(Exprim é en dinars)', 0.9576495885848999)],
 [[[396.0, 311.0], [480.0, 311.0], [480.0, 342.0], [396.0, 342.0]],
  ('ACTF', 0.9566921591758728)],
 [[[819.0, 311.0], [889.0, 311.0], [889.0, 342.0], [819.0, 342.0]],
  ('Note', 0.9988561272621155)],
 [[[999.0, 311.0], [1074.0, 311.0], [1074.0, 342.0], [999.0, 342.0]],
  ('2016', 0.9999121427536011)],
 [[[1263.0, 311.0], [1336.0, 311.0], [1336.0, 342.0], [1263.0, 342.0]],
  ('2016', 0.9999305009841919)],
 [[[71.0, 395.0], [440.0, 397.0], [440.0, 435.0], [70.0, 433.0]],
  ('ACTFS NON COURANTS', 0.9968974590301514)],
 [[[106.0, 446.0], [475.0, 446.0], [475.0, 475.0], [106.0, 475.0]],
  ('In m obilisations Incorporelles', 0.9825693368911743)],
 [[[834.0, 446.0], [861.0, 446.0], [861.0, 483.0], [834.0, 483.0]],
  ('1', 0.9997937083244324)],
 [[[1010.0, 448.0], [1162.0, 448.0], [1162.0, 472.0], [1010.0, 472.0]],
  ('124228,846', 0.9925972819328308)],
 [[[1283.0, 446.0], [1428.0, 446.0], [1428.0, 477.0], [1283.0, 477.0]],
  ('93 886,846', 0.9996631741523743)],
 [[[101.0, 488.0], [396.0, 488.0], [396.0, 517.0], [101.0, 517.0]],
  ('Moins: am ortissem ents', 0.9916755557060242)],
 [[[1015.0, 486.0], [1164.0, 486.0], [1164.0, 517.0], [1015.0, 517.0]],
  ('-91 294,410', 0.9991706609725952)],
 [[[1275.0, 483.0], [1427.0, 488.0], [1426.0, 519.0], [1274.0, 514.0]],
  ('-78 068,362', 0.9994400143623352)],
 [[[62.0, 534.0], [537.0, 534.0], [537.0, 563.0], [62.0, 563.0]],
  ('Totaldes In m obilisations ncorporelles', 0.9806383848190308)],
 [[[1006.0, 532.0], [1164.0, 532.0], [1164.0, 563.0], [1006.0, 563.0]],
  ('32 934,436', 0.9987757802009583)],
 [[[1272.0, 534.0], [1426.0, 534.0], [1426.0, 558.0], [1272.0, 558.0]],
  ('15 818,484', 0.9695286750793457)],
 [[[104.0, 616.0], [458.0, 618.0], [458.0, 649.0], [103.0, 647.0]],
  ('In m obilisations Corporelles', 0.9905821681022644)],
 [[[834.0, 616.0], [861.0, 616.0], [861.0, 656.0], [834.0, 656.0]],
  ('2', 0.9994760155677795)],
 [[[968.0, 618.0], [1164.0, 618.0], [1164.0, 647.0], [968.0, 647.0]],
  ('15 237 277,298', 0.9976374506950378)],
 [[[1232.0, 618.0], [1426.0, 618.0], [1426.0, 647.0], [1232.0, 647.0]],
  ('14 564 622,909', 0.9978256821632385)],
 [[[106.0, 662.0], [390.0, 662.0], [390.0, 684.0], [106.0, 684.0]],
  ('Moins:am ortissem ents', 0.9625549912452698)],
 [[[977.0, 660.0], [1164.0, 660.0], [1164.0, 689.0], [977.0, 689.0]],
  ('-7 533 768,451', 0.9994535446166992)],
 [[[1241.0, 660.0], [1426.0, 660.0], [1426.0, 689.0], [1241.0, 689.0]],
  ('-6 994 676,216', 0.9986059069633484)],
 [[[62.0, 706.0], [519.0, 706.0], [519.0, 735.0], [62.0, 735.0]],
  ('Totaldes In m obilisations Corporelles', 0.9908503293991089)],
 [[[966.0, 704.0], [1164.0, 704.0], [1164.0, 733.0], [966.0, 733.0]],
  ('7 703 508,847', 0.9931225180625916)],
 [[[1230.0, 704.0], [1426.0, 704.0], [1426.0, 733.0], [1230.0, 733.0]],
  ('7 569 946,693', 0.9961235523223877)],
 [[[106.0, 790.0], [445.0, 790.0], [445.0, 819.0], [106.0, 819.0]],
  ('In m obilisation Financieres', 0.9414507746696472)],
 [[[834.0, 790.0], [861.0, 790.0], [861.0, 826.0], [834.0, 826.0]],
  ('3', 0.998200535774231)],
 [[[984.0, 790.0], [1164.0, 790.0], [1164.0, 819.0], [984.0, 819.0]],
  ('4 026 555,120', 0.9961666464805603)],
 [[[1246.0, 790.0], [1428.0, 790.0], [1428.0, 821.0], [1246.0, 821.0]],
  ('4 036 000,816', 0.9987364411354065)],
 [[[99.0, 830.0], [324.0, 832.0], [323.0, 863.0], [99.0, 861.0]],
  ('Moins: provisions', 0.9982004761695862)],
 [[[1030.0, 830.0], [1164.0, 830.0], [1164.0, 861.0], [1030.0, 861.0]],
  ('-6 700,000', 0.9969855546951294)],
 [[[1292.0, 830.0], [1428.0, 830.0], [1428.0, 861.0], [1292.0, 861.0]],
  ('-6 700,000', 0.9991105198860168)],
 [[[62.0, 879.0], [519.0, 879.0], [519.0, 907.0], [62.0, 907.0]],
  ('Totaldes In m obilisations Financires', 0.9961878657341003)],
 [[[968.0, 876.0], [1164.0, 876.0], [1164.0, 905.0], [968.0, 905.0]],
  ('4 019 855,120', 0.998183012008667)],
 [[[1230.0, 876.0], [1428.0, 876.0], [1428.0, 905.0], [1230.0, 905.0]],
  ('4 029 300,816', 0.9939902424812317)],
 [[[163.0, 962.0], [497.0, 962.0], [497.0, 991.0], [163.0, 991.0]],
  ('Autres actifs non courants', 0.9979398250579834)],
 [[[1087.0, 960.0], [1166.0, 960.0], [1166.0, 991.0], [1087.0, 991.0]],
  ('0,000', 0.9977569580078125)],
 [[[1347.0, 960.0], [1431.0, 960.0], [1431.0, 991.0], [1347.0, 991.0]],
  ('0,000', 0.995051383972168)],
 [[[114.0, 1009.0], [515.0, 1009.0], [515.0, 1037.0], [114.0, 1037.0]],
  ('Tota1des Actifs Non Courants', 0.9856941103935242)],
 [[[951.0, 1007.0], [1164.0, 1007.0], [1164.0, 1035.0], [951.0, 1035.0]],
  ('11 756 298,403', 0.9861313104629517)],
 [[[1213.0, 1007.0], [1428.0, 1007.0], [1428.0, 1035.0], [1213.0, 1035.0]],
  ('11 615 065,993', 0.9979842901229858)],
 [[[70.0, 1077.0], [361.0, 1077.0], [361.0, 1108.0], [70.0, 1108.0]],
  ('ACTFS COURANTS', 0.9705931544303894)],
 [[[86.0, 1148.0], [176.0, 1148.0], [176.0, 1179.0], [86.0, 1179.0]],
  ('Stocks', 0.9993359446525574)],
 [[[966.0, 1148.0], [1162.0, 1145.0], [1162.0, 1176.0], [966.0, 1179.0]],
  ('23 106 479,322', 0.9480529427528381)],
 [[[1232.0, 1152.0], [1426.0, 1152.0], [1426.0, 1174.0], [1232.0, 1174.0]],
  ('17822532,694', 0.9901010990142822)],
 [[[86.0, 1192.0], [306.0, 1192.0], [306.0, 1223.0], [86.0, 1223.0]],
  ('Moins: provisions', 0.9734849333763123)],
 [[[1087.0, 1190.0], [1166.0, 1190.0], [1166.0, 1223.0], [1087.0, 1223.0]],
  ('0,000', 0.9957376718521118)],
 [[[1347.0, 1190.0], [1431.0, 1190.0], [1431.0, 1221.0], [1347.0, 1221.0]],
  ('0,000', 0.9989597201347351)],
 [[[948.0, 1234.0], [1162.0, 1232.0], [1162.0, 1262.0], [949.0, 1265.0]],
  ('23 106 479,322', 0.998519778251648)],
 [[[1213.0, 1236.0], [1428.0, 1236.0], [1428.0, 1265.0], [1213.0, 1265.0]],
  ('17 822 532,694', 0.9985901713371277)],
 [[[86.0, 1318.0], [456.0, 1320.0], [455.0, 1351.0], [86.0, 1349.0]],
  ('Clients et Com ptes rattachés', 0.9950974583625793)],
 [[[984.0, 1320.0], [1166.0, 1320.0], [1166.0, 1351.0], [984.0, 1351.0]],
  ('6 154 493,174', 0.9903929829597473)],
 [[[1244.0, 1318.0], [1429.0, 1320.0], [1428.0, 1351.0], [1243.0, 1349.0]],
  ('5 064 455,614', 0.9979642033576965)],
 [[[86.0, 1364.0], [306.0, 1364.0], [306.0, 1393.0], [86.0, 1393.0]],
  ('Moins: provisions', 0.9974320530891418)],
 [[[979.0, 1362.0], [1164.0, 1362.0], [1164.0, 1391.0], [979.0, 1391.0]],
  ('-3 816 340,102', 0.9949828386306763)],
 [[[1239.0, 1360.0], [1424.0, 1362.0], [1424.0, 1393.0], [1239.0, 1390.0]],
  ('-3 879 471,402', 0.9988775849342346)],
 [[[964.0, 1404.0], [1164.0, 1406.0], [1164.0, 1437.0], [964.0, 1435.0]],
  ('2 338 153,072', 0.9805315732955933)],
 [[[1226.0, 1404.0], [1422.0, 1406.0], [1422.0, 1437.0], [1226.0, 1435.0]],
  ('1 184 984,212', 0.9949784874916077)],
 [[[88.0, 1494.0], [365.0, 1494.0], [365.0, 1523.0], [88.0, 1523.0]],
  ('Autres actifs courants', 0.9989429116249084)],
 [[[834.0, 1494.0], [861.0, 1494.0], [861.0, 1525.0], [834.0, 1525.0]],
  ('4', 0.9996094107627869)],
 [[[984.0, 1492.0], [1164.0, 1492.0], [1164.0, 1523.0], [984.0, 1523.0]],
  ('4 231 705,435', 0.988227128982544)],
 [[[1246.0, 1494.0], [1426.0, 1494.0], [1426.0, 1523.0], [1246.0, 1523.0]],
  ('3 550 953,311', 0.9949556589126587)],
 [[[86.0, 1536.0], [308.0, 1536.0], [308.0, 1565.0], [86.0, 1565.0]],
  ('Moins: provisions', 0.9984766840934753)],
 [[[1032.0, 1536.0], [1162.0, 1536.0], [1162.0, 1561.0], [1032.0, 1561.0]],
  ('8 582,158', 0.969651460647583)],
 [[[1294.0, 1534.0], [1426.0, 1534.0], [1426.0, 1565.0], [1294.0, 1565.0]],
  ('8 582,158', 0.9993050694465637)],
 [[[968.0, 1578.0], [1162.0, 1578.0], [1162.0, 1609.0], [968.0, 1609.0]],
  ('4 223 123,277', 0.9948821663856506)],
 [[[1228.0, 1578.0], [1424.0, 1578.0], [1424.0, 1609.0], [1228.0, 1609.0]],
  ('3 542 371,153', 0.9996162056922913)],
 [[[88.0, 1667.0], [566.0, 1667.0], [566.0, 1695.0], [88.0, 1695.0]],
  ('Placem ents et autres actifs financiers', 0.9846656918525696)],
 [[[838.0, 1659.0], [865.0, 1666.0], [854.0, 1705.0], [828.0, 1698.0]],
  ('5', 0.9969195127487183)],
 [[[982.0, 1667.0], [1164.0, 1667.0], [1164.0, 1695.0], [982.0, 1695.0]],
  ('3 724 668,343', 0.9879812598228455)],
 [[[1246.0, 1667.0], [1428.0, 1667.0], [1428.0, 1695.0], [1246.0, 1695.0]],
  ('3 650 000,000', 0.9707531332969666)],
 [[[86.0, 1708.0], [306.0, 1708.0], [306.0, 1737.0], [86.0, 1737.0]],
  ('Moins: provisions', 0.9974320530891418)],
 [[[1087.0, 1706.0], [1164.0, 1706.0], [1164.0, 1737.0], [1087.0, 1737.0]],
  ('0,000', 0.9996231198310852)],
 [[[1347.0, 1706.0], [1428.0, 1706.0], [1428.0, 1737.0], [1347.0, 1737.0]],
  ('0,000', 0.9986527562141418)],
 [[[964.0, 1748.0], [1162.0, 1750.0], [1162.0, 1781.0], [964.0, 1779.0]],
  ('3 724 668,343', 0.9799537658691406)],
 [[[1226.0, 1748.0], [1426.0, 1750.0], [1426.0, 1781.0], [1226.0, 1779.0]],
  ('3 650 000,000', 0.9763182401657104)],
 [[[88.0, 1839.0], [563.0, 1839.0], [563.0, 1867.0], [88.0, 1867.0]],
  ('Liquidités et équivalents de liquidités', 0.9820231199264526)],
 [[[838.0, 1832.0], [865.0, 1839.0], [857.0, 1871.0], [830.0, 1865.0]],
  ('6', 0.9956406354904175)],
 [[[984.0, 1839.0], [1164.0, 1839.0], [1164.0, 1867.0], [984.0, 1867.0]],
  ('3 857 342,895', 0.9871515035629272)],
 [[[1246.0, 1839.0], [1428.0, 1839.0], [1428.0, 1867.0], [1246.0, 1867.0]],
  ('3 317 149,491', 0.999221682548523)],
 [[[114.0, 1925.0], [456.0, 1925.0], [456.0, 1953.0], [114.0, 1953.0]],
  ('Totaldes Actifs Courants', 0.9806938171386719)],
 [[[951.0, 1925.0], [1164.0, 1925.0], [1164.0, 1953.0], [951.0, 1953.0]],
  ('37 249 766,909', 0.9951285719871521)],
 [[[1211.0, 1920.0], [1424.0, 1923.0], [1424.0, 1954.0], [1210.0, 1951.0]],
  ('29 517 037,550', 0.9698621034622192)],
 [[[71.0, 2017.0], [366.0, 2022.0], [365.0, 2053.0], [70.0, 2048.0]],
  ('TOTAL DESACTFS', 0.9886757135391235)],
 [[[951.0, 2026.0], [1162.0, 2026.0], [1162.0, 2055.0], [951.0, 2055.0]],
  ('49 006 065,312', 0.9927746653556824)],
 [[[1213.0, 2026.0], [1426.0, 2026.0], [1426.0, 2055.0], [1213.0, 2055.0]],
  ('41 132 103,543', 0.9857695698738098)]]

In [ ]:
from paddleocr import PaddleOCR, draw_ocr

In [ ]:
ocr = PaddleOCR(lang='fr')
image_path = 'ext_im.jpg'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)[0]

[2024/04/27 15:56:32] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/latin/latin_PP-OCRv3_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.10/dist-packages/paddleocr/ppocr/utils/dict/latin_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=False, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='fr', det=True, rec=True, type='ocr', ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2024/04/27 15:56:33] ppocr WARNING: Since the angle classifier is not initialized, it will not be used during the forward process
[2024/04/27 15:56:33] ppocr DEBUG: dt_boxes num : 88, elapsed : 0.3306148052215576
[2024/04/27 15:56:36] ppocr DEBUG: rec_res num  : 88, elapsed : 3.4223241806030273

In [ ]:
print(output)

[[[[447.0, 190.0], [1050.0, 190.0], [1050.0, 221.0], [447.0, 221.0]], ('BILAN C0NS0LDE au 31/12/2017', 0.9731495976448059)], [[[614.0, 263.0], [889.0, 263.0], [889.0, 291.0], [614.0, 291.0]], ('(Exprim é en dinars)', 0.9576495885848999)], [[[396.0, 311.0], [480.0, 311.0], [480.0, 342.0], [396.0, 342.0]], ('ACTF', 0.9566921591758728)], [[[819.0, 311.0], [889.0, 311.0], [889.0, 342.0], [819.0, 342.0]], ('Note', 0.9988561272621155)], [[[999.0, 311.0], [1074.0, 311.0], [1074.0, 342.0], [999.0, 342.0]], ('2016', 0.9999121427536011)], [[[1263.0, 311.0], [1336.0, 311.0], [1336.0, 342.0], [1263.0, 342.0]], ('2016', 0.9999305009841919)], [[[71.0, 395.0], [440.0, 397.0], [440.0, 435.0], [70.0, 433.0]], ('ACTFS NON COURANTS', 0.9968974590301514)], [[[106.0, 446.0], [475.0, 446.0], [475.0, 475.0], [106.0, 475.0]], ('In m obilisations Incorporelles', 0.9825693368911743)], [[[834.0, 446.0], [861.0, 446.0], [861.0, 483.0], [834.0, 483.0]], ('1', 0.9997937083244324)], [[[1010.0, 448.0], [1162.0, 448.0], [1162.0, 472.0], [1010.0, 472.0]], ('124228,846', 0.9925972819328308)], [[[1283.0, 446.0], [1428.0, 446.0], [1428.0, 477.0], [1283.0, 477.0]], ('93 886,846', 0.9996631741523743)], [[[101.0, 488.0], [396.0, 488.0], [396.0, 517.0], [101.0, 517.0]], ('Moins: am ortissem ents', 0.9916755557060242)], [[[1015.0, 486.0], [1164.0, 486.0], [1164.0, 517.0], [1015.0, 517.0]], ('-91 294,410', 0.9991706609725952)], [[[1275.0, 483.0], [1427.0, 488.0], [1426.0, 519.0], [1274.0, 514.0]], ('-78 068,362', 0.9994400143623352)], [[[62.0, 534.0], [537.0, 534.0], [537.0, 563.0], [62.0, 563.0]], ('Totaldes In m obilisations ncorporelles', 0.9806383848190308)], [[[1006.0, 532.0], [1164.0, 532.0], [1164.0, 563.0], [1006.0, 563.0]], ('32 934,436', 0.9987757802009583)], [[[1272.0, 534.0], [1426.0, 534.0], [1426.0, 558.0], [1272.0, 558.0]], ('15 818,484', 0.9695286750793457)], [[[104.0, 616.0], [458.0, 618.0], [458.0, 649.0], [103.0, 647.0]], ('In m obilisations Corporelles', 0.9905821681022644)], [[[834.0, 616.0], [861.0, 616.0], [861.0, 656.0], [834.0, 656.0]], ('2', 0.9994760155677795)], [[[968.0, 618.0], [1164.0, 618.0], [1164.0, 647.0], [968.0, 647.0]], ('15 237 277,298', 0.9976374506950378)], [[[1232.0, 618.0], [1426.0, 618.0], [1426.0, 647.0], [1232.0, 647.0]], ('14 564 622,909', 0.9978256821632385)], [[[106.0, 662.0], [390.0, 662.0], [390.0, 684.0], [106.0, 684.0]], ('Moins:am ortissem ents', 0.9625549912452698)], [[[977.0, 660.0], [1164.0, 660.0], [1164.0, 689.0], [977.0, 689.0]], ('-7 533 768,451', 0.9994535446166992)], [[[1241.0, 660.0], [1426.0, 660.0], [1426.0, 689.0], [1241.0, 689.0]], ('-6 994 676,216', 0.9986059069633484)], [[[62.0, 706.0], [519.0, 706.0], [519.0, 735.0], [62.0, 735.0]], ('Totaldes In m obilisations Corporelles', 0.9908503293991089)], [[[966.0, 704.0], [1164.0, 704.0], [1164.0, 733.0], [966.0, 733.0]], ('7 703 508,847', 0.9931225180625916)], [[[1230.0, 704.0], [1426.0, 704.0], [1426.0, 733.0], [1230.0, 733.0]], ('7 569 946,693', 0.9961235523223877)], [[[106.0, 790.0], [445.0, 790.0], [445.0, 819.0], [106.0, 819.0]], ('In m obilisation Financieres', 0.9414507746696472)], [[[834.0, 790.0], [861.0, 790.0], [861.0, 826.0], [834.0, 826.0]], ('3', 0.998200535774231)], [[[984.0, 790.0], [1164.0, 790.0], [1164.0, 819.0], [984.0, 819.0]], ('4 026 555,120', 0.9961666464805603)], [[[1246.0, 790.0], [1428.0, 790.0], [1428.0, 821.0], [1246.0, 821.0]], ('4 036 000,816', 0.9987364411354065)], [[[99.0, 830.0], [324.0, 832.0], [323.0, 863.0], [99.0, 861.0]], ('Moins: provisions', 0.9982004761695862)], [[[1030.0, 830.0], [1164.0, 830.0], [1164.0, 861.0], [1030.0, 861.0]], ('-6 700,000', 0.9969855546951294)], [[[1292.0, 830.0], [1428.0, 830.0], [1428.0, 861.0], [1292.0, 861.0]], ('-6 700,000', 0.9991105198860168)], [[[62.0, 879.0], [519.0, 879.0], [519.0, 907.0], [62.0, 907.0]], ('Totaldes In m obilisations Financires', 0.9961878657341003)], [[[968.0, 876.0], [1164.0, 876.0], [1164.0, 905.0], [968.0, 905.0]], ('4 019 855,120', 0.998183012008667)], [[[1230.0, 876.0], [1428.0, 876.0], [1428.0, 905.0], [1230.0, 905.0]], ('4 029 300,816', 0.9939902424812317)], [[[163.0, 962.0], [497.0, 962.0], [497.0, 991.0], [163.0, 991.0]], ('Autres actifs non courants', 0.9979398250579834)], [[[1087.0, 960.0], [1166.0, 960.0], [1166.0, 991.0], [1087.0, 991.0]], ('0,000', 0.9977569580078125)], [[[1347.0, 960.0], [1431.0, 960.0], [1431.0, 991.0], [1347.0, 991.0]], ('0,000', 0.995051383972168)], [[[114.0, 1009.0], [515.0, 1009.0], [515.0, 1037.0], [114.0, 1037.0]], ('Tota1des Actifs Non Courants', 0.9856941103935242)], [[[951.0, 1007.0], [1164.0, 1007.0], [1164.0, 1035.0], [951.0, 1035.0]], ('11 756 298,403', 0.9861313104629517)], [[[1213.0, 1007.0], [1428.0, 1007.0], [1428.0, 1035.0], [1213.0, 1035.0]], ('11 615 065,993', 0.9979842901229858)], [[[70.0, 1077.0], [361.0, 1077.0], [361.0, 1108.0], [70.0, 1108.0]], ('ACTFS COURANTS', 0.9705931544303894)], [[[86.0, 1148.0], [176.0, 1148.0], [176.0, 1179.0], [86.0, 1179.0]], ('Stocks', 0.9993359446525574)], [[[966.0, 1148.0], [1162.0, 1145.0], [1162.0, 1176.0], [966.0, 1179.0]], ('23 106 479,322', 0.9480529427528381)], [[[1232.0, 1152.0], [1426.0, 1152.0], [1426.0, 1174.0], [1232.0, 1174.0]], ('17822532,694', 0.9901010990142822)], [[[86.0, 1192.0], [306.0, 1192.0], [306.0, 1223.0], [86.0, 1223.0]], ('Moins: provisions', 0.9734849333763123)], [[[1087.0, 1190.0], [1166.0, 1190.0], [1166.0, 1223.0], [1087.0, 1223.0]], ('0,000', 0.9957376718521118)], [[[1347.0, 1190.0], [1431.0, 1190.0], [1431.0, 1221.0], [1347.0, 1221.0]], ('0,000', 0.9989597201347351)], [[[948.0, 1234.0], [1162.0, 1232.0], [1162.0, 1262.0], [949.0, 1265.0]], ('23 106 479,322', 0.998519778251648)], [[[1213.0, 1236.0], [1428.0, 1236.0], [1428.0, 1265.0], [1213.0, 1265.0]], ('17 822 532,694', 0.9985901713371277)], [[[86.0, 1318.0], [456.0, 1320.0], [455.0, 1351.0], [86.0, 1349.0]], ('Clients et Com ptes rattachés', 0.9950974583625793)], [[[984.0, 1320.0], [1166.0, 1320.0], [1166.0, 1351.0], [984.0, 1351.0]], ('6 154 493,174', 0.9903929829597473)], [[[1244.0, 1318.0], [1429.0, 1320.0], [1428.0, 1351.0], [1243.0, 1349.0]], ('5 064 455,614', 0.9979642033576965)], [[[86.0, 1364.0], [306.0, 1364.0], [306.0, 1393.0], [86.0, 1393.0]], ('Moins: provisions', 0.9974320530891418)], [[[979.0, 1362.0], [1164.0, 1362.0], [1164.0, 1391.0], [979.0, 1391.0]], ('-3 816 340,102', 0.9949828386306763)], [[[1239.0, 1360.0], [1424.0, 1362.0], [1424.0, 1393.0], [1239.0, 1390.0]], ('-3 879 471,402', 0.9988775849342346)], [[[964.0, 1404.0], [1164.0, 1406.0], [1164.0, 1437.0], [964.0, 1435.0]], ('2 338 153,072', 0.9805315732955933)], [[[1226.0, 1404.0], [1422.0, 1406.0], [1422.0, 1437.0], [1226.0, 1435.0]], ('1 184 984,212', 0.9949784874916077)], [[[88.0, 1494.0], [365.0, 1494.0], [365.0, 1523.0], [88.0, 1523.0]], ('Autres actifs courants', 0.9989429116249084)], [[[834.0, 1494.0], [861.0, 1494.0], [861.0, 1525.0], [834.0, 1525.0]], ('4', 0.9996094107627869)], [[[984.0, 1492.0], [1164.0, 1492.0], [1164.0, 1523.0], [984.0, 1523.0]], ('4 231 705,435', 0.988227128982544)], [[[1246.0, 1494.0], [1426.0, 1494.0], [1426.0, 1523.0], [1246.0, 1523.0]], ('3 550 953,311', 0.9949556589126587)], [[[86.0, 1536.0], [308.0, 1536.0], [308.0, 1565.0], [86.0, 1565.0]], ('Moins: provisions', 0.9984766840934753)], [[[1032.0, 1536.0], [1162.0, 1536.0], [1162.0, 1561.0], [1032.0, 1561.0]], ('8 582,158', 0.969651460647583)], [[[1294.0, 1534.0], [1426.0, 1534.0], [1426.0, 1565.0], [1294.0, 1565.0]], ('8 582,158', 0.9993050694465637)], [[[968.0, 1578.0], [1162.0, 1578.0], [1162.0, 1609.0], [968.0, 1609.0]], ('4 223 123,277', 0.9948821663856506)], [[[1228.0, 1578.0], [1424.0, 1578.0], [1424.0, 1609.0], [1228.0, 1609.0]], ('3 542 371,153', 0.9996162056922913)], [[[88.0, 1667.0], [566.0, 1667.0], [566.0, 1695.0], [88.0, 1695.0]], ('Placem ents et autres actifs financiers', 0.9846656918525696)], [[[838.0, 1659.0], [865.0, 1666.0], [854.0, 1705.0], [828.0, 1698.0]], ('5', 0.9969195127487183)], [[[982.0, 1667.0], [1164.0, 1667.0], [1164.0, 1695.0], [982.0, 1695.0]], ('3 724 668,343', 0.9879812598228455)], [[[1246.0, 1667.0], [1428.0, 1667.0], [1428.0, 1695.0], [1246.0, 1695.0]], ('3 650 000,000', 0.9707531332969666)], [[[86.0, 1708.0], [306.0, 1708.0], [306.0, 1737.0], [86.0, 1737.0]], ('Moins: provisions', 0.9974320530891418)], [[[1087.0, 1706.0], [1164.0, 1706.0], [1164.0, 1737.0], [1087.0, 1737.0]], ('0,000', 0.9996231198310852)], [[[1347.0, 1706.0], [1428.0, 1706.0], [1428.0, 1737.0], [1347.0, 1737.0]], ('0,000', 0.9986527562141418)], [[[964.0, 1748.0], [1162.0, 1750.0], [1162.0, 1781.0], [964.0, 1779.0]], ('3 724 668,343', 0.9799537658691406)], [[[1226.0, 1748.0], [1426.0, 1750.0], [1426.0, 1781.0], [1226.0, 1779.0]], ('3 650 000,000', 0.9763182401657104)], [[[88.0, 1839.0], [563.0, 1839.0], [563.0, 1867.0], [88.0, 1867.0]], ('Liquidités et équivalents de liquidités', 0.9820231199264526)], [[[838.0, 1832.0], [865.0, 1839.0], [857.0, 1871.0], [830.0, 1865.0]], ('6', 0.9956406354904175)], [[[984.0, 1839.0], [1164.0, 1839.0], [1164.0, 1867.0], [984.0, 1867.0]], ('3 857 342,895', 0.9871515035629272)], [[[1246.0, 1839.0], [1428.0, 1839.0], [1428.0, 1867.0], [1246.0, 1867.0]], ('3 317 149,491', 0.999221682548523)], [[[114.0, 1925.0], [456.0, 1925.0], [456.0, 1953.0], [114.0, 1953.0]], ('Totaldes Actifs Courants', 0.9806938171386719)], [[[951.0, 1925.0], [1164.0, 1925.0], [1164.0, 1953.0], [951.0, 1953.0]], ('37 249 766,909', 0.9951285719871521)], [[[1211.0, 1920.0], [1424.0, 1923.0], [1424.0, 1954.0], [1210.0, 1951.0]], ('29 517 037,550', 0.9698621034622192)], [[[71.0, 2017.0], [366.0, 2022.0], [365.0, 2053.0], [70.0, 2048.0]], ('TOTAL DESACTFS', 0.9886757135391235)], [[[951.0, 2026.0], [1162.0, 2026.0], [1162.0, 2055.0], [951.0, 2055.0]], ('49 006 065,312', 0.9927746653556824)], [[[1213.0, 2026.0], [1426.0, 2026.0], [1426.0, 2055.0], [1213.0, 2055.0]], ('41 132 103,543', 0.9857695698738098)]]

In [ ]:
boxes = [line[0] for line in output]
texts = [line[1][0] for line in output]
probabilities = [line[1][1] for line in output]

In [ ]:
image_boxes = image_cv.copy()

In [ ]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes, text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [ ]:
cv2.imwrite('detections.jpg', image_boxes)

True

In [ ]:
texts

['BILAN C0NS0LDE au 31/12/2017',
 '(Exprim é en dinars)',
 'ACTF',
 'Note',
 '2016',
 '2016',
 'ACTFS NON COURANTS',
 'In m obilisations Incorporelles',
 '1',
 '124228,846',
 '93 886,846',
 'Moins: am ortissem ents',
 '-91 294,410',
 '-78 068,362',
 'Totaldes In m obilisations ncorporelles',
 '32 934,436',
 '15 818,484',
 'In m obilisations Corporelles',
 '2',
 '15 237 277,298',
 '14 564 622,909',
 'Moins:am ortissem ents',
 '-7 533 768,451',
 '-6 994 676,216',
 'Totaldes In m obilisations Corporelles',
 '7 703 508,847',
 '7 569 946,693',
 'In m obilisation Financieres',
 '3',
 '4 026 555,120',
 '4 036 000,816',
 'Moins: provisions',
 '-6 700,000',
 '-6 700,000',
 'Totaldes In m obilisations Financires',
 '4 019 855,120',
 '4 029 300,816',
 'Autres actifs non courants',
 '0,000',
 '0,000',
 'Tota1des Actifs Non Courants',
 '11 756 298,403',
 '11 615 065,993',
 'ACTFS COURANTS',
 'Stocks',
 '23 106 479,322',
 '17822532,694',
 'Moins: provisions',
 '0,000',
 '0,000',
 '23 106 479,322',
 '17 822 532,694',
 'Clients et Com ptes rattachés',
 '6 154 493,174',
 '5 064 455,614',
 'Moins: provisions',
 '-3 816 340,102',
 '-3 879 471,402',
 '2 338 153,072',
 '1 184 984,212',
 'Autres actifs courants',
 '4',
 '4 231 705,435',
 '3 550 953,311',
 'Moins: provisions',
 '8 582,158',
 '8 582,158',
 '4 223 123,277',
 '3 542 371,153',
 'Placem ents et autres actifs financiers',
 '5',
 '3 724 668,343',
 '3 650 000,000',
 'Moins: provisions',
 '0,000',
 '0,000',
 '3 724 668,343',
 '3 650 000,000',
 'Liquidités et équivalents de liquidités',
 '6',
 '3 857 342,895',
 '3 317 149,491',
 'Totaldes Actifs Courants',
 '37 249 766,909',
 '29 517 037,550',
 'TOTAL DESACTFS',
 '49 006 065,312',
 '41 132 103,543']

# Reconstruction

## Get Horizontal and Vertical Lines

In [ ]:
im = image_cv.copy()

In [ ]:
horiz_boxes = []
vert_boxes = []

for box in boxes:
  x_h, x_v = 0,int(box[0][0])
  y_h, y_v = int(box[0][1]),0
  width_h,width_v = image_width, int(box[2][0]-box[0][0])
  height_h,height_v = int(box[2][1]-box[0][1]),image_height

  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h), (x_h+width_h,y_h+height_h),(0,0,255),1)
  cv2.rectangle(im,(x_v,y_v), (x_v+width_v,y_v+height_v),(0,255,0),1)

In [ ]:
cv2.imwrite('horiz_vert.jpg',im)

True

## Non-Max Suppression

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [ ]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)

[ 0  1  5  6  8 13 15 18 22 26 30 33 35 37 42 43 44 49 51 54 57 59 61 66
 68 70 74 76 81 83 86]

In [ ]:
im_nms = image_cv.copy()

In [ ]:
for val in horiz_lines:
  cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)

In [ ]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [ ]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [ ]:
print(vert_out)

tf.Tensor([ 5  4  8 74 44 49 37  0], shape=(8,), dtype=int32)

In [ ]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[ 0  4  5  8 37 44 49 74]

In [ ]:
for val in vert_lines:
  cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])),(255,0,0),1)

In [ ]:
cv2.imwrite('im_nms.jpg',im_nms)

True

## Convert to CSV

In [ ]:
out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(31, 8)
[['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '']]

In [ ]:
unordered_boxes = []

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[447, 0, 1050, 2119]
[999, 0, 1074, 2119]
[1263, 0, 1336, 2119]
[834, 0, 861, 2119]
[163, 0, 497, 2119]
[86, 0, 176, 2119]
[1347, 0, 1431, 2119]
[1087, 0, 1164, 2119]

In [ ]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[5 4 0 3 1 7 2 6]

In [ ]:
def intersection(box_1, box_2):
  return [box_2[0], box_1[1],box_2[2], box_1[3]]

In [ ]:
def iou(box_1, box_2):

  x_1 = max(box_1[0], box_2[0])
  y_1 = max(box_1[1], box_2[1])
  x_2 = min(box_1[2], box_2[2])
  y_2 = min(box_1[3], box_2[3])

  inter = abs(max((x_2 - x_1, 0)) * max((y_2 - y_1), 0))
  if inter == 0:
      return 0

  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))

  return inter / float(box_1_area + box_2_area - inter)

In [ ]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant = intersection(horiz_boxes[horiz_lines[i]], vert_boxes[vert_lines[ordered_boxes[j]]] )

    for b in range(len(boxes)):
      the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if(iou(resultant,the_box)>0.1):
        out_array[i][j] = texts[b]

In [ ]:
out_array=np.array(out_array)

In [ ]:
out_array

array([['', '', 'BILAN C0NS0LDE au 31/12/2017', '', '', '', '', ''],
       ['', '', '(Exprim é en dinars)', '', '', '', '', ''],
       ['', 'ACTF', 'Note', 'Note', '2016', '', '2016', ''],
       ['ACTFS NON COURANTS', 'ACTFS NON COURANTS', '', '', '', '', '',
        ''],
       ['In m obilisations Incorporelles',
        'In m obilisations Incorporelles', '', '1', '124228,846',
        '124228,846', '93 886,846', '93 886,846'],
       ['Moins: am ortissem ents', 'Moins: am ortissem ents', '', '',
        '-91 294,410', '-91 294,410', '-78 068,362', '-78 068,362'],
       ['Totaldes In m obilisations ncorporelles',
        'Totaldes In m obilisations ncorporelles', '', '', '32 934,436',
        '32 934,436', '15 818,484', '15 818,484'],
       ['In m obilisations Corporelles', 'In m obilisations Corporelles',
        '', '2', '15 237 277,298', '15 237 277,298', '14 564 622,909',
        '14 564 622,909'],
       ['Moins:am ortissem ents', 'Moins:am ortissem ents',
        '-7 533 768,451', '', '-7 533 768,451', '-7 533 768,451',
        '-6 994 676,216', '-6 994 676,216'],
       ['Totaldes In m obilisations Corporelles',
        'Totaldes In m obilisations Corporelles', '7 703 508,847', '',
        '7 703 508,847', '7 703 508,847', '7 569 946,693',
        '7 569 946,693'],
       ['In m obilisation Financieres', 'In m obilisation Financieres',
        '', '3', '4 026 555,120', '4 026 555,120', '4 036 000,816',
        '4 036 000,816'],
       ['Moins: provisions', 'Moins: provisions', '', '', '-6 700,000',
        '-6 700,000', '-6 700,000', '-6 700,000'],
       ['Totaldes In m obilisations Financires',
        'Totaldes In m obilisations Financires', '4 019 855,120', '',
        '4 019 855,120', '4 019 855,120', '4 029 300,816',
        '4 029 300,816'],
       ['', 'Autres actifs non courants', '', '', '', '0,000', '',
        '0,000'],
       ['Tota1des Actifs Non Courants', 'Tota1des Actifs Non Courants',
        '11 756 298,403', '', '11 756 298,403', '11 756 298,403',
        '11 615 065,993', '11 615 065,993'],
       ['ACTFS COURANTS', 'ACTFS COURANTS', '', '', '', '', '', ''],
       ['Stocks', '', '23 106 479,322', '', '23 106 479,322',
        '23 106 479,322', '17822532,694', '17822532,694'],
       ['Moins: provisions', 'Moins: provisions', '', '', '', '0,000',
        '', '0,000'],
       ['', '', '23 106 479,322', '', '23 106 479,322', '23 106 479,322',
        '17 822 532,694', '17 822 532,694'],
       ['Clients et Com ptes rattachés', 'Clients et Com ptes rattachés',
        '', '', '6 154 493,174', '6 154 493,174', '5 064 455,614',
        '5 064 455,614'],
       ['Moins: provisions', 'Moins: provisions', '', '',
        '-3 816 340,102', '-3 816 340,102', '-3 879 471,402',
        '-3 879 471,402'],
       ['', '', '2 338 153,072', '', '2 338 153,072', '2 338 153,072',
        '1 184 984,212', '1 184 984,212'],
       ['Autres actifs courants', 'Autres actifs courants', '', '4',
        '4 231 705,435', '4 231 705,435', '3 550 953,311',
        '3 550 953,311'],
       ['Moins: provisions', 'Moins: provisions', '', '', '8 582,158',
        '8 582,158', '8 582,158', '8 582,158'],
       ['', '', '4 223 123,277', '', '4 223 123,277', '4 223 123,277',
        '3 542 371,153', '3 542 371,153'],
       ['Placem ents et autres actifs financiers',
        'Placem ents et autres actifs financiers', '', '5',
        '3 724 668,343', '3 724 668,343', '3 650 000,000',
        '3 650 000,000'],
       ['Moins: provisions', 'Moins: provisions', '', '', '', '0,000',
        '', '0,000'],
       ['', '', '3 724 668,343', '', '3 724 668,343', '3 724 668,343',
        '3 650 000,000', '3 650 000,000'],
       ['Liquidités et équivalents de liquidités',
        'Liquidités et équivalents de liquidités',
        'Liquidités et équivalents de liquidités', '6', '3 857 342,895',
        '3 857 342,895', '3 317 149,491', '3 317 149,491'],
       ['Totaldes Actifs Courants', 'Totaldes Actifs Courants',
        '37 249 766,909', '', '37 249 766,909', '37 249 766,909',
        '29 517 037,550', '29 517 037,550'],
       ['TOTAL DESACTFS', 'TOTAL DESACTFS', '49 006 065,312', '',
        '49 006 065,312', '49 006 065,312', '41 132 103,543',
        '41 132 103,543']], dtype='<U39')

Entity Ruler Method

In [ ]:
# import spacy
# from spacy.pipeline import EntityRuler

# # Initialize the spaCy model for French language
# nlp = spacy.blank("fr")

# # Create the EntityRuler and add it to the pipeline
# entity_ruler = nlp.add_pipe("entity_ruler")

# # Define the patterns for the entity ruler as done previously
# patterns = [
#     {"label": "ACTIF", "pattern": "Espèces et avoirs auprès des banques centrales"},
#     {"label": "ACTIF", "pattern": "Créances sur les établissements de crédit"},
#     {"label": "ACTIF", "pattern": "Créances sur la clientèle"},
#     {"label": "ACTIF", "pattern": "Portefeuille-titres commercial"},
#     {"label": "ACTIF", "pattern": "Portefeuille d'investissement"},
#     {"label": "ACTIF", "pattern": "Immobilisations"},
#     {"label": "ACTIF", "pattern": "Autres actifs"},
# ]

In [ ]:
# # Add the patterns to the entity ruler
# entity_ruler.add_patterns(patterns)

# # Function to apply entity ruler to a column in a DataFrame and return a list of entities
# def apply_entity_ruler_to_dataframe(df, column_name):
#     entities_list = []
#     for item in df[column_name]:
#         doc = nlp(str(item))  # Make sure to convert to string in case the items are not
#         entities = [(ent.text, ent.label_) for ent in doc.ents]
#         entities_list.append(entities)
#     return entities_list

# # Replace 'your_dataframe' with the name of your actual DataFrame and 'Column_Name' with the actual column name
# # For example, if the first column is named 'Account', replace 'Column_Name' with 'Account'
# your_dataframe = None  # Placeholder for the actual DataFrame
# entities_column = apply_entity_ruler_to_dataframe(your_dataframe, 'Column_Name')

# # Add the identified entities as a new column in the DataFrame
# your_dataframe['Identified Entities'] = entities_column

# # Now, your_dataframe will contain a new column 'Identified Entities' with the entities identified by the entity ruler

#1)postprocessing with nlp

In [ ]:
!pip install -U 'spacy[cuda11x]'

Requirement already satisfied: spacy[cuda11x] in /usr/local/lib/python3.10/dist-packages (3.7.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (8.2.3)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (0.9.4)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (4.66.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (2.7.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (3.1.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (24.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (3.3.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy[cuda11x]) (1.25.2)
Collecting cupy-cuda11x<13.0.0,>=11.0.0 (from spacy[cuda11x])
  Downloading cupy_cuda11x-12.3.0-cp310-cp310-manylinux2014_x86_64.whl (89.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 MB 3.5 MB/s eta 0:00:00
Requirement already satisfied: fastrlock>=0.5 in /usr/local/lib/python3.10/dist-packages (from cupy-cuda11x<13.0.0,>=11.0.0->spacy[cuda11x]) (0.8.2)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda11x]) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda11x]) (2.18.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda11x]) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda11x]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda11x]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda11x]) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda11x]) (2024.2.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy[cuda11x]) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy[cuda11x]) (0.1.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy[cuda11x]) (8.1.7)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.4.0,>=0.1.0->spacy[cuda11x]) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy[cuda11x]) (2.1.5)
Installing collected packages: cupy-cuda11x
Successfully installed cupy-cuda11x-12.3.0

In [ ]:
!python -m spacy download fr_core_news_sm

/usr/local/lib/python3.10/dist-packages/cupy/_environment.py:447: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''
/usr/local/lib/python3.10/dist-packages/cupy/_environment.py:447: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''
/usr/local/lib/python3.10/dist-packages/cupy/_environment.py:447: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''
/usr/local/lib/python3.10/dist-packages/cupy/_environment.py:447: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''
Collecting fr-core-news-sm==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.7.0/fr_core_news_sm-3.7.0-py3-none-any.whl (16.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 17.8 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from fr-core-news-sm==3.7.0) (3.7.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (8.2.3)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (0.9.4)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (4.66.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2.7.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (3.1.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (24.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (3.3.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (1.25.2)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2.18.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2024.2.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (0.1.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (8.1.7)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.4.0,>=0.1.0->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.0->fr-core-news-sm==3.7.0) (2.1.5)
Installing collected packages: fr-core-news-sm
Successfully installed fr-core-news-sm-3.7.0
✔ Download and installation successful
You can now load the package via spacy.load('fr_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
! pip install spacyfrom collections

ERROR: Could not find a version that satisfies the requirement spacyfrom (from versions: none)
ERROR: No matching distribution found for spacyfrom

In [ ]:
#import spacyfrom collections import defaultdict
from spacy.lang.fr.examples import sentences

/usr/local/lib/python3.10/dist-packages/cupy/_environment.py:447: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''
/usr/local/lib/python3.10/dist-packages/cupy/_environment.py:447: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''
/usr/local/lib/python3.10/dist-packages/cupy/_environment.py:447: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''
/usr/local/lib/python3.10/dist-packages/cupy/_environment.py:447: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''

In [ ]:
new_out_array=[["L'Arab Banking Corporation Tunisie -ABC Tunisie- publie ci-dessous, ses états financiers arretés au",
        "L'Arab Banking Corporation Tunisie -ABC Tunisie- publie ci-dessous, ses états financiers arretés au",
        '', '', ''],
       ["31 décembre 2016 tels qu'ils seront soumis a I'approbation de I'assemblée générale ordinaire qui se tiendra en date du",
        "31 décembre 2016 tels qu'ils seront soumis a I'approbation de I'assemblée générale ordinaire qui se tiendra en date du",
        '', '', ''],
       ['17 mai 2017. Ces états sont accompagnés des rapports général et spécial des commissaires aux comptes, Mme',
        '17 mai 2017. Ces états sont accompagnés des rapports général et spécial des commissaires aux comptes, Mme',
        '', '', '']]

In [ ]:
nlp = spacy.load("fr_core_news_sm")

In [ ]:
import spacy
from sklearn.metrics.pairwise import cosine_similarity
from collections import defaultdict
import numpy as np

In [ ]:
# Tokenize the OCR output using spaCy
tokens = []
for row in new_out_array:
    tokens.extend([token.text for token in nlp(' '.join(row))])

# Initialize a dictionary to store word vectors
word_vectors = defaultdict()

# Compute word embeddings and store them in the dictionary
for token in tokens:
    if token not in word_vectors:
        word_vectors[token] = nlp(token).vector

# Define a similarity threshold (adjust as needed)
similarity_threshold = 0.9

# Remove duplicates based on similarity
unique_tokens = []
seen = set()
for token in tokens:
    if token not in seen:
        unique_tokens.append(token)
        seen.add(token)
    else:
        # Check similarity with previously seen tokens
        is_duplicate = False
        for seen_token in seen:
            similarity = cosine_similarity([word_vectors[token]], [word_vectors[seen_token]])[0][0]
            if similarity > similarity_threshold:
                is_duplicate = True
                break
        if not is_duplicate:
            unique_tokens.append(token)
            seen.add(token)

# Output the unique tokens
unique_text = ' '.join(unique_tokens)
print(unique_text)

L' Arab Banking Corporation Tunisie -ABC Tunisie- publie ci-dessous , ses états financiers arretés au    31 décembre 2016 tels qu' ils seront soumis a I' approbation de assemblée générale ordinaire qui se tiendra en date du 17 mai 2017 . Ces sont accompagnés des rapports général et spécial commissaires aux comptes Mme

#2)postprocessing with nlp

In [ ]:
# # Split each element using the character ','
# ocr_output_split = [element.split(',') for element in new_out_array[0]]

In [ ]:
# ocr_output_split

In [ ]:
# # Calculate similarity between the two phrases
# phrase1 = ocr_output_split[0][0].strip()  # Remove leading and trailing whitespace
# phrase2 = ocr_output_split[1][0].strip()  # Remove leading and trailing whitespace

In [ ]:
# phrase2

In [ ]:
# # Tokenize the phrases using spaCy
# tokens1 = [token.text for token in nlp(phrase1)]
# tokens2 = [token.text for token in nlp(phrase2)]

In [ ]:
# # Convert the token lists to spaCy Doc objects for similarity calculation
# doc1 = nlp(' '.join(tokens1))
# doc2 = nlp(' '.join(tokens2))

In [ ]:
# # Compute the similarity between the two phrases
# similarity = doc1.similarity(doc2)

In [ ]:
# print("Similarity between the two phrases:", similarity)

# Convert to CSV

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(out_array)

,0,1,2,3,4,5,6,7
0,,,BILAN C0NS0LDE au 31/12/2017,,,,,
1,,,(Exprim é en dinars),,,,,
2,,ACTF,Note,Note,2016,,2016,
3,ACTFS NON COURANTS,ACTFS NON COURANTS,,,,,,
4,In m obilisations Incorporelles,In m obilisations Incorporelles,,1,"124228,846","124228,846","93 886,846","93 886,846"
5,Moins: am ortissem ents,Moins: am ortissem ents,,,"-91 294,410","-91 294,410","-78 068,362","-78 068,362"
6,Totaldes In m obilisations ncorporelles,Totaldes In m obilisations ncorporelles,,,"32 934,436","32 934,436","15 818,484","15 818,484"
7,In m obilisations Corporelles,In m obilisations Corporelles,,2,"15 237 277,298","15 237 277,298","14 564 622,909","14 564 622,909"
8,Moins:am ortissem ents,Moins:am ortissem ents,"-7 533 768,451",,"-7 533 768,451","-7 533 768,451","-6 994 676,216","-6 994 676,216"
9,Totaldes In m obilisations Corporelles,Totaldes In m obilisations Corporelles,"7 703 508,847",,"7 703 508,847","7 703 508,847","7 569 946,693","7 569 946,693"
10,In m obilisation Financieres,In m obilisation Financieres,,3,"4 026 555,120","4 026 555,120","4 036 000,816","4 036 000,816"
11,Moins: provisions,Moins: provisions,,,"-6 700,000","-6 700,000","-6 700,000","-6 700,000"
12,Totaldes In m obilisations Financires,Totaldes In m obilisations Financires,"4 019 855,120",,"4 019 855,120","4 019 855,120","4 029 300,816","4 029 300,816"
13,,Autres actifs non courants,,,,"0,000",,"0,000"
14,Tota1des Actifs Non Courants,Tota1des Actifs Non Courants,"11 756 298,403",,"11 756 298,403","11 756 298,403","11 615 065,993","11 615 065,993"
15,ACTFS COURANTS,ACTFS COURANTS,,,,,,
16,Stocks,,"23 106 479,322",,"23 106 479,322","23 106 479,322","17822532,694","17822532,694"
17,Moins: provisions,Moins: provisions,,,,"0,000",,"0,000"
18,,,"23 106 479,322",,"23 106 479,322","23 106 479,322","17 822 532,694","17 822 532,694"
19,Clients et Com ptes rattachés,Clients et Com ptes rattachés,,,"6 154 493,174","6 154 493,174","5 064 455,614","5 064 455,614"
20,Moins: provisions,Moins: provisions,,,"-3 816 340,102","-3 816 340,102","-3 879 471,402","-3 879 471,402"
21,,,"2 338 153,072",,"2 338 153,072","2 338 153,072","1 184 984,212","1 184 984,212"
22,Autres actifs courants,Autres actifs courants,,4,"4 231 705,435","4 231 705,435","3 550 953,311","3 550 953,311"
23,Moins: provisions,Moins: provisions,,,"8 582,158","8 582,158","8 582,158","8 582,158"
24,,,"4 223 123,277",,"4 223 123,277","4 223 123,277","3 542 371,153","3 542 371,153"
25,Placem ents et autres actifs financiers,Placem ents et autres actifs financiers,,5,"3 724 668,343","3 724 668,343","3 650 000,000","3 650 000,000"
26,Moins: provisions,Moins: provisions,,,,"0,000",,"0,000"
27,,,"3 724 668,343",,"3 724 668,343","3 724 668,343","3 650 000,000","3 650 000,000"
28,Liquidités et équivalents de liquidités,Liquidités et équivalents de liquidités,Liquidités et équivalents de liquidités,6,"3 857 342,895","3 857 342,895","3 317 149,491","3 317 149,491"
29,Totaldes Actifs Courants,Totaldes Actifs Courants,"37 249 766,909",,"37 249 766,909","37 249 766,909","29 517 037,550","29 517 037,550"
30,TOTAL DESACTFS,TOTAL DESACTFS,"49 006 065,312",,"49 006 065,312","49 006 065,312","41 132 103,543","41 132 103,543"

In [ ]:
pd.DataFrame(out_array).to_csv('sample.csv')

In [ ]:
out_array_list = out_array.tolist()

In [ ]:
import json
json_data = json.dumps(out_array_list, ensure_ascii=False)

In [ ]:
# Write the JSON data to a file
with open('sample.json', 'w') as f:
    f.write(json_data)

#postprocessing with python

In [ ]:
# Initialiser un ensemble pour stocker les phrases déjà vues
seen_phrases = set()

# Parcourir chaque sous-liste dans la liste de listes
for row in out_array:
    # Initialiser une liste temporaire pour stocker les phrases uniques dans cette sous-liste
    unique_row = []
    # Parcourir chaque phrase dans la sous-liste actuelle
    for phrase in row:
        # Nettoyer la phrase en enlevant les espaces inutiles et en la mettant en minuscules
        cleaned_phrase = phrase.strip().lower()
        # Vérifier si la phrase n'a pas déjà été vue
        if cleaned_phrase not in seen_phrases:
            # Ajouter la phrase à l'ensemble des phrases vues
            seen_phrases.add(cleaned_phrase)
            # Ajouter la phrase à la liste temporaire des phrases uniques
            unique_row.append(phrase)
        else:
            # Si la phrase a déjà été vue, la laisser vide
            unique_row.append('')
    # Remplacer la sous-liste actuelle par la liste temporaire des phrases uniques
    row[:] = unique_row

# Afficher le résultat
for row in out_array:
    print(row)

In [ ]:
# def replace_second_duplicate_with_empty(lst):
#     seen = {}
#     for i, item in enumerate(lst):
#         if item in seen:
#             seen[item] += 1
#             if seen[item] == 2:
#                 for j in range(i, -1, -1):
#                     if lst[j] == item:
#                         lst[j] = ''
#                         break
#         else:
#             seen[item] = 1
#     return lst

# # Example usage:
# original_list =['PR01Marges et revenus assimilés',
#         'PR01Marges et revenus assimilés', '', '5.1', '52088 374',
#         '38 279 737', '81 363 612']
# updated_list = replace_second_duplicate_with_empty(original_list)
# print(updated_list)

In [ ]:
import csv
import pandas as pd

In [ ]:
def replace_second_duplicate_with_empty(lst):
    seen = {}
    for inner_list in lst:
        for i, item in enumerate(inner_list):
            if item in seen:
                seen[item] += 1
                if seen[item] == 2:
                    for j in range(i, -1, -1):
                        if inner_list[j] == item:
                            inner_list[j] = ''
                            break
            else:
                seen[item] = 1
    return lst

updated_array = replace_second_duplicate_with_empty(out_array)
print(updated_array)

[['' '' 'BILAN C0NS0LDE au 31/12/2017' '' '' '' '' '']
 ['' '' '(Exprim é en dinars)' '' '' '' '' '']
 ['' 'ACTF' 'Note' '' '2016' '' '' '']
 ['ACTFS NON COURANTS' '' '' '' '' '' '' '']
 ['In m obilisations Incorporelles' '' '' '1' '124228,846' ''
  '93 886,846' '']
 ['Moins: am ortissem ents' '' '' '' '-91 294,410' '' '-78 068,362' '']
 ['Totaldes In m obilisations ncorporelles' '' '' '' '32 934,436' ''
  '15 818,484' '']
 ['In m obilisations Corporelles' '' '' '2' '15 237 277,298' ''
  '14 564 622,909' '']
 ['Moins:am ortissem ents' '' '-7 533 768,451' '' '' '-7 533 768,451'
  '-6 994 676,216' '']
 ['Totaldes In m obilisations Corporelles' '' '7 703 508,847' '' ''
  '7 703 508,847' '7 569 946,693' '']
 ['In m obilisation Financieres' '' '' '3' '4 026 555,120' ''
  '4 036 000,816' '']
 ['Moins: provisions' '' '' '' '-6 700,000' '' '-6 700,000' '-6 700,000']
 ['Totaldes In m obilisations Financires' '' '4 019 855,120' '' ''
  '4 019 855,120' '4 029 300,816' '']
 ['' 'Autres actifs non courants' '' '' '' '0,000' '' '']
 ['Tota1des Actifs Non Courants' '' '11 756 298,403' '' ''
  '11 756 298,403' '11 615 065,993' '']
 ['ACTFS COURANTS' '' '' '' '' '' '' '']
 ['Stocks' '' '23 106 479,322' '' '' '23 106 479,322' '17822532,694' '']
 ['Moins: provisions' 'Moins: provisions' '' '' '' '0,000' '' '0,000']
 ['' '' '23 106 479,322' '' '23 106 479,322' '23 106 479,322'
  '17 822 532,694' '']
 ['Clients et Com ptes rattachés' '' '' '' '6 154 493,174' ''
  '5 064 455,614' '']
 ['Moins: provisions' 'Moins: provisions' '' '' '-3 816 340,102' ''
  '-3 879 471,402' '']
 ['' '' '2 338 153,072' '' '' '2 338 153,072' '1 184 984,212' '']
 ['Autres actifs courants' '' '' '4' '4 231 705,435' '' '3 550 953,311'
  '']
 ['Moins: provisions' 'Moins: provisions' '' '' '8 582,158' ''
  '8 582,158' '8 582,158']
 ['' '' '4 223 123,277' '' '' '4 223 123,277' '3 542 371,153' '']
 ['Placem ents et autres actifs financiers' '' '' '5' '3 724 668,343' ''
  '3 650 000,000' '']
 ['Moins: provisions' 'Moins: provisions' '' '' '' '0,000' '' '0,000']
 ['' '' '3 724 668,343' '' '3 724 668,343' '3 724 668,343'
  '3 650 000,000' '3 650 000,000']
 ['Liquidités et équivalents de liquidités' ''
  'Liquidités et équivalents de liquidités' '6' '3 857 342,895' ''
  '3 317 149,491' '']
 ['Totaldes Actifs Courants' '' '37 249 766,909' '' '' '37 249 766,909'
  '29 517 037,550' '']
 ['TOTAL DESACTFS' '' '49 006 065,312' '' '' '49 006 065,312'
  '41 132 103,543' '']]

In [ ]:
df=pd.DataFrame(out_array)

In [ ]:
df

,0,1,2,3,4,5,6,7
0,,,BILAN C0NS0LDE au 31/12/2017,,,,,
1,,,(Exprim é en dinars),,,,,
2,,ACTF,Note,,2016,,,
3,ACTFS NON COURANTS,,,,,,,
4,In m obilisations Incorporelles,,,1,"124228,846",,"93 886,846",
5,Moins: am ortissem ents,,,,"-91 294,410",,"-78 068,362",
6,Totaldes In m obilisations ncorporelles,,,,"32 934,436",,"15 818,484",
7,In m obilisations Corporelles,,,2,"15 237 277,298",,"14 564 622,909",
8,Moins:am ortissem ents,,"-7 533 768,451",,,"-7 533 768,451","-6 994 676,216",
9,Totaldes In m obilisations Corporelles,,"7 703 508,847",,,"7 703 508,847","7 569 946,693",
10,In m obilisation Financieres,,,3,"4 026 555,120",,"4 036 000,816",
11,Moins: provisions,,,,"-6 700,000",,"-6 700,000","-6 700,000"
12,Totaldes In m obilisations Financires,,"4 019 855,120",,,"4 019 855,120","4 029 300,816",
13,,Autres actifs non courants,,,,"0,000",,
14,Tota1des Actifs Non Courants,,"11 756 298,403",,,"11 756 298,403","11 615 065,993",
15,ACTFS COURANTS,,,,,,,
16,Stocks,,"23 106 479,322",,,"23 106 479,322","17822532,694",
17,Moins: provisions,Moins: provisions,,,,"0,000",,"0,000"
18,,,"23 106 479,322",,"23 106 479,322","23 106 479,322","17 822 532,694",
19,Clients et Com ptes rattachés,,,,"6 154 493,174",,"5 064 455,614",
20,Moins: provisions,Moins: provisions,,,"-3 816 340,102",,"-3 879 471,402",
21,,,"2 338 153,072",,,"2 338 153,072","1 184 984,212",
22,Autres actifs courants,,,4,"4 231 705,435",,"3 550 953,311",
23,Moins: provisions,Moins: provisions,,,"8 582,158",,"8 582,158","8 582,158"
24,,,"4 223 123,277",,,"4 223 123,277","3 542 371,153",
25,Placem ents et autres actifs financiers,,,5,"3 724 668,343",,"3 650 000,000",
26,Moins: provisions,Moins: provisions,,,,"0,000",,"0,000"
27,,,"3 724 668,343",,"3 724 668,343","3 724 668,343","3 650 000,000","3 650 000,000"
28,Liquidités et équivalents de liquidités,,Liquidités et équivalents de liquidités,6,"3 857 342,895",,"3 317 149,491",
29,Totaldes Actifs Courants,,"37 249 766,909",,,"37 249 766,909","29 517 037,550",
30,TOTAL DESACTFS,,"49 006 065,312",,,"49 006 065,312","41 132 103,543",

In [ ]:
def dataframe_to_json(df, file_path=None, orient='records', **kwargs):
    if file_path:
        df.to_json(file_path, orient=orient, force_ascii=False, **kwargs)
    else:
        return df.to_json(orient=orient, force_ascii=False, **kwargs)

In [ ]:
# Convert DataFrame to JSON
json_string = dataframe_to_json(df)
print(json_string)

[{"0":"","1":"BILAN","2":"","3":"","4":""},{"0":"","1":"","2":"(montants exprimés en dinar tunisien)","3":"","4":""},{"0":"","1":"","2":"","3":"Exercice clos au","4":""},{"0":"ACTIFS","1":"Notes","2":"30\/06\/2014","3":"30\/06\/2013","4":"31\/12\/2013"},{"0":"ACTIFS NON COURANTS","1":"","2":"","3":"","4":""},{"0":"Actifs immobilisés","1":"","2":"","3":"","4":""},{"0":"Immobilisations incorporelles","1":"4","2":"2469102","3":"2 326 128","4":"2 373 050"},{"0":"Moins : amortissements","1":"","2":"(1 653 942)","3":"(1 455 774)","4":"(1 575 313)"},{"0":"","1":"","2":"815 160","3":"870 354","4":"797 737"},{"0":"Immobilisations corporelles","1":"","2":"43182493","3":"38 259 095","4":"40009902"},{"0":"Moins : amortissements & provisions","1":"","2":"(27 573 768)","3":"(25 431 065)(26 443 651)","4":""},{"0":"","1":"","2":"15 608 725","3":"12 828 030","4":"13 566 251"},{"0":"Immobilisations financiéres","1":"4","2":"109 460","3":"72 202","4":"78 101"},{"0":"Moins : provisions","1":"","2":"","3":"","4":""},{"0":"","1":"","2":"","3":"","4":""},{"0":"Total des actifs immobilisés","1":"","2":"16 533 345","3":"13 770 586","4":"14 442 089"},{"0":"Autres actifs non courants","1":"5","2":"61 718","3":"","4":"82 291"},{"0":"Total des actifs non courants","1":"","2":"16 595 063","3":"","4":"14 524 380"},{"0":"ACTIFS COURANTS","1":"","2":"","3":"","4":""},{"0":"Stocks","1":"6","2":"27781275","3":"29 461 906","4":"33 622 019"},{"0":"","1":"","2":"(1 051 098)","3":"(1 067 842)","4":"(945 967)"},{"0":"","1":"","2":"26 730 178","3":"28 394 065","4":"32 676 052"},{"0":"Clients et comptes rattachés","1":"7","2":"9 506 760","3":"14 851 006","4":"10 194 345"},{"0":"Moins : provisions","1":"","2":"(415 037)","3":"(415 693)","4":""},{"0":"","1":"","2":"9 091 723","3":"14 435 313","4":"9779308"},{"0":"Autres actifs courants","1":"8","2":"2 617497","3":"1 406 896","4":"3 061 452"},{"0":"Moins : provisions","1":"","2":"","3":"","4":""},{"0":"","1":"","2":"2 617 497","3":"","4":""},{"0":"Placements et autres actifs financiers","1":"9","2":"2050137","3":"2 101 986","4":"2 045 257"},{"0":"Liquidités et équivalents de liquidités","1":"10","2":"217 998","3":"142 662","4":"50 882"},{"0":"Total des actifs courants","1":"","2":"40707 533","3":"46 480 923","4":"47 612 951"},{"0":"Total des actifs","1":"","2":"57 302 596","3":"60 251 509","4":"62 137 332"}]

In [ ]:
import json
# Parse the JSON string
data = json.loads(json_string)

# Extract values corresponding to key "1"
values = [(item.get("0"), item.get("1")) for item in data]

print(values)

[('', 'BILAN'), ('', ''), ('', ''), ('ACTIFS', 'Notes'), ('ACTIFS NON COURANTS', ''), ('Actifs immobilisés', ''), ('Immobilisations incorporelles', '4'), ('Moins : amortissements', ''), ('', ''), ('Immobilisations corporelles', ''), ('Moins : amortissements & provisions', ''), ('', ''), ('Immobilisations financiéres', '4'), ('Moins : provisions', ''), ('', ''), ('Total des actifs immobilisés', ''), ('Autres actifs non courants', '5'), ('Total des actifs non courants', ''), ('ACTIFS COURANTS', ''), ('Stocks', '6'), ('', ''), ('', ''), ('Clients et comptes rattachés', '7'), ('Moins : provisions', ''), ('', ''), ('Autres actifs courants', '8'), ('Moins : provisions', ''), ('', ''), ('Placements et autres actifs financiers', '9'), ('Liquidités et équivalents de liquidités', '10'), ('Total des actifs courants', ''), ('Total des actifs', '')]

In [ ]:
tuples_with_numbers = [(item[0], item[1]) for item in values if any(char.isdigit() for char in item[1])]
print(tuples_with_numbers)

[('Immobilisations incorporelles', '4'), ('Immobilisations financiéres', '4'), ('Autres actifs non courants', '5'), ('Stocks', '6'), ('Clients et comptes rattachés', '7'), ('Autres actifs courants', '8'), ('Placements et autres actifs financiers', '9'), ('Liquidités et équivalents de liquidités', '10')]

In [ ]:
elements_list = [list(item) for item in tuples_with_numbers]

print(elements_list)

[['Immobilisations incorporelles', '4'], ['Immobilisations financiéres', '4'], ['Autres actifs non courants', '5'], ['Stocks', '6'], ['Clients et comptes rattachés', '7'], ['Autres actifs courants', '8'], ['Placements et autres actifs financiers', '9'], ['Liquidités et équivalents de liquidités', '10']]

In [ ]:
extracted_list = []
for sublist in elements_list:
    for item in sublist:
        extracted_list.append(item)

print(extracted_list)

['Immobilisations incorporelles', '4', 'Immobilisations financiéres', '4', 'Autres actifs non courants', '5', 'Stocks', '6', 'Clients et comptes rattachés', '7', 'Autres actifs courants', '8', 'Placements et autres actifs financiers', '9', 'Liquidités et équivalents de liquidités', '10']

In [ ]:
output_without_numbers = [item for item in extracted_list if not any(char.isdigit() for char in item)]

print(output_without_numbers)

['Immobilisations incorporelles', 'Immobilisations financiéres', 'Autres actifs non courants', 'Stocks', 'Clients et comptes rattachés', 'Autres actifs courants', 'Placements et autres actifs financiers', 'Liquidités et équivalents de liquidités']

In [ ]:
# Rechercher l'élément JSON contenant les valeurs des dates
date_element = None
for item in data:
    if item.get("2") and item.get("3") and item.get("4"):
        date_element = item
        break

# Extraire les valeurs de date uniquement
dates = [date_element[key] for key in ['2', '3', '4']]

In [ ]:
dates

['30/06/2014', '30/06/2013', '31/12/2013']

In [ ]:
import json
# Parse the JSON string
data = json.loads(json_string)

# Extract values corresponding to key "1"
values = [item.get("1") for item in data]

print(values)


import re
# Extract numeric values using regular expressions
numeric_values = [re.sub(r'[^\d]', '', value) for value in values if re.sub(r'[^\d]', '', value)]

print(numeric_values)

['BILAN', '', '', 'Notes', '', '', '4', '', '', '', '', '', '4', '', '', '', '5', '', '', '6', '', '', '7', '', '', '8', '', '', '9', '10', '', '']
['4', '4', '5', '6', '7', '8', '9', '10']

In [ ]:
concatenated_data = dates + output_without_numbers
print(concatenated_data)

['30/06/2014', '30/06/2013', '31/12/2013', 'Immobilisations incorporelles', 'Immobilisations financiéres', 'Autres actifs non courants', 'Stocks', 'Clients et comptes rattachés', 'Autres actifs courants', 'Placements et autres actifs financiers', 'Liquidités et équivalents de liquidités']

In [ ]:
!pip install pytesseract

Collecting pytesseract
  Downloading pytesseract-0.3.10-py3-none-any.whl (14 kB)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from pytesseract) (24.0)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from pytesseract) (9.4.0)
Installing collected packages: pytesseract
Successfully installed pytesseract-0.3.10

In [ ]:
!sudo apt install tesseract-ocr

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 45 not upgraded.
Need to get 4,816 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-eng all 1:4.00~git30-7274cfa-1.1 [1,591 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-osd all 1:4.00~git30-7274cfa-1.1 [2,990 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr amd64 4.1.1-2.1build1 [236 kB]
Fetched 4,816 kB in 0s (22.9 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package tesseract-ocr-eng.
(Reading database ... 121752 files and directories currently installed.)
Preparing to unpack .../tesseract-ocr-eng_1%3a4.00~git30-7274cfa-1.1_all.deb ...
Unpacking tesseract-ocr-eng (1:4.00~git30-7274cfa-1.1) ...
Selecting previously unselected package tesseract-ocr-osd.
Preparing to unpack .../tesseract-ocr-osd_1%3a4.00~git30-7274cfa-1.1_all.deb ...
Unpacking tesseract-ocr-osd (1:4.00~git30-7274cfa-1.1) ...
Selecting previously unselected package tesseract-ocr.
Preparing to unpack .../tesseract-ocr_4.1.1-2.1build1_amd64.deb ...
Unpacking tesseract-ocr (4.1.1-2.1build1) ...
Setting up tesseract-ocr-eng (1:4.00~git30-7274cfa-1.1) ...
Setting up tesseract-ocr-osd (1:4.00~git30-7274cfa-1.1) ...
Setting up tesseract-ocr (4.1.1-2.1build1) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
!pip install PyPDF2
!pip install pdf2image

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 3.6 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from pdf2image) (9.4.0)
Installing collected packages: pdf2image
Successfully installed pdf2image-1.17.0

In [ ]:
!apt-get update
!apt-get install poppler-utils

Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1,691 kB]
Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Get:8 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,082 kB]
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [808 kB]
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,375 kB]
Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [27.8 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,974 kB]
Fetched 7,210 kB in 2s (3,227 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 45 not upgraded.
Need to get 186 kB of archives.
After this operation, 696 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.3 [186 kB]
Fetched 186 kB in 0s (1,854 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 121799 files and directories currently installed.)
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.3_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.3) ...
Setting up poppler-utils (22.02.0-2ubuntu0.3) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
import PyPDF2
from pdf2image import convert_from_path
import cv2
import numpy as np
import pytesseract
import io
import os
import re  # Import du module re pour les expressions régulières

In [ ]:

def has_notes(text):
    exclude_keywords = ['bilan', 'bilan consolidé',
                        'total actif', 'total passif', 'total des actif', 'total des passif',
                        "total de l'actif", "total des passifs", 'total actifs', 'total passifs', 'total des actifs',
                        "hors bilan",'etat de resultat','etats de resultat','etat de résultat',"etat de flux de trésorerie",
                        "etat de flux de tresorerie", "etat de variation de l'actif net trimestriel","etats de variation de l'actif net",
                        "etat des flux de trésorerie", "etat des flux de tresorerie"]


    for total_keyword in extracted_list:
        if re.search(r'\b{}\b'.format(total_keyword), text, re.IGNORECASE):
            if not any(re.search(r'\b{}\b'.format(exclude_keyword), text, re.IGNORECASE) for exclude_keyword in exclude_keywords):
               return True
    return False

def find_and_save_note_data(pdf_file_path, output_file_path):
    try:
        print("Processing:", pdf_file_path)
        found_bilan = False
        writer = PyPDF2.PdfWriter()

        with open(pdf_file_path, 'rb') as file:
            reader = PyPDF2.PdfReader(file)
            for page_num, page in enumerate(reader.pages):
                text = page.extract_text()
                if has_notes(text):
                    found_bilan = True
                    writer.add_page(page)

        # If bilan is not found using text extraction, try OCR for each page
        if not found_bilan:
            print("note not found using text extraction. Trying OCR.")
            images = convert_from_path(pdf_file_path)

            for img_num, img in enumerate(images):
                gray = cv2.cvtColor(np.array(img), cv2.COLOR_BGR2GRAY)
                extracted_text = pytesseract.image_to_string(gray)

                if has_notes(extracted_text):
                    found_bilan = True
                    img_bytes = io.BytesIO()
                    img.save(img_bytes, format='PDF')
                    writer.add_page(PyPDF2.PdfReader(img_bytes).pages[0])

        if found_bilan:
            with open(output_file_path, 'wb') as output_file:
                writer.write(output_file)
            print("notes data saved to:", output_file_path)
        else:
            print("No 'notes' found in the PDF:", pdf_file_path)

    except Exception as e:
        print("An error occurred while processing the PDF file:", e)

input_dir = "/content/drive/MyDrive/new"  # Chemin du répertoire contenant les fichiers PDF
output_dir = "/content/drive/MyDrive/output/notes"

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for filename in os.listdir(input_dir):
    if filename.endswith('.pdf'):
        pdf_file_path = os.path.join(input_dir, filename)
        output_filename = os.path.basename(pdf_file_path)
        output_file_path = os.path.join(output_dir, output_filename)
        find_and_save_note_data(pdf_file_path, output_file_path)

Processing: /content/drive/MyDrive/new/abc_efd311216.pdf
notes data saved to: /content/drive/MyDrive/output/notes/abc_efd311216.pdf
Processing: /content/drive/MyDrive/new/ADWYA_EFI300614.pdf
notes data saved to: /content/drive/MyDrive/output/notes/ADWYA_EFI300614.pdf

In [ ]:
# # Alternatively, save to a file
# dataframe_to_json(df, 'data.json')

In [ ]:
pd.DataFrame(out_array).to_csv('sample.csv')

Extracting table notes with LLM : LLAMA 2

In [ ]:
!pip install replicate

Set API Replicate Token

In [ ]:
import os
os.environ["REPLICATE_API_TOKEN"]="r8_4Sjym90opWUqzkPXT7sIM9aqFo0DJOF0ia3up"

Run LLAMA 2 Model

In [ ]:
import replicate

# Prompts
pre_prompt = "You are a helpful assistant. You do not respond as 'User' or pretend to be 'User'. You only respond once as 'Assistant'."
prompt_input = "What is Streamlit?"

# Generate LLM response
output = replicate.run('a16z-infra/llama13b-v2-chat:df7690f1994d94e96ad9d568eac121aecf50684a0b0963b25a41cc40061269e5', # LLM model
                        input={"prompt": f"{pre_prompt} {prompt_input} Assistant: ", # Prompts
                        "temperature":0.1, "top_p":0.9, "max_length":128, "repetition_penalty":1})  # Model parameters

In [ ]:
output

In [ ]:
full_response = ""

for item in output:
  full_response += item

print(full_response)

LLAMA 2 with rag

In [ ]:
! git clone https://github.com/meta-llama/codellama

In [ ]:
!pip install -q -U bitsandbytes
!pip install -q -U git+https://github.com/huggingface/transformers.git
!pip install -q -U git+https://github.com/huggingface/peft.git
!pip install -q -U git+https://github.com/huggingface/accelerate.git

## Merging Cells

In [ ]:
current_bank=['']*len(out_array[0,:])
print(current_bank)

In [ ]:
def empty(arr):
  for i in arr:
    if i=='':
      return True
  return False

In [ ]:
cleaned_array=[]

In [ ]:
for i in range(len(out_array)):
  if not empty(out_array[i]):
    current_bank=[out_array[i][j] for j in range(len(out_array[i]))]
    cleaned_array.append(current_bank)
    not_empty=True
  else:
    for j in range(len(out_array[i])):
      current_bank[j]+=' '+out_array[i][j]
    print('-->',current_bank)
cleaned_array=np.array(cleaned_array)
print(cleaned_array)

In [ ]:
pd.DataFrame(cleaned_array).to_csv('cleaned.csv')

# Convert to OWL Format

# **CSV to Text**

In [ ]:
import  jpype
import  asposecells


jpype.startJVM()
from asposecells.api import Workbook

workbook = Workbook("/content/sample.csv")
workbook.save("Output.docx")
jpype.shutdownJVM()

# Brighten Image (For Anyone dealing with PDFs created from scanned images)

In [ ]:
from PIL import Image, ImageEnhance

#read the image
im = Image.open("ext_im.jpg")

#image brightness enhancer
enhancer = ImageEnhance.Brightness(im)

factor = 1 #gives original image
im_output = enhancer.enhance(factor)
im_output.save('ext_im-1.jpg')

factor = 1.5## brightens the image
im_output = enhancer.enhance(factor)
im_output.save('ext_im-2.jpg')